### ISSUE TITLE
Option pandoc_template unrecognised

### ISSUE THREAD

**Issue by mfoulds** [alexandre-perrin/mkdocs-pandoc-plugin#8]
I've just installed `mkdocs-pandoc-plugin` and the pandoc_template keyword isn't recognised.

`WARNING  -  Config value 'plugins': Plugin 'pandoc' option 'pandoc_template': Unrecognised configuration name: pandoc_template`

My `mkdocs.yml` settings are as below:

```yaml
plugins:
  - search
  - pandoc:          # requires mkdocs-pandoc-plugin
      # enabled_if_env: ENABLE_PANDOC_EXPORT
      combined: true
      combined_output_path: pandoc/combined.pdf
      pandoc_template: eisvogel
```
