### ISSUE TITLE
pdf generated as .pdf.md and attempting to convert pdfs 

### ISSUE THREAD

**Issue by mfoulds** [alexandre-perrin/mkdocs-pandoc-plugin#9]
Hi - I've noticed two problems when running `mkdocs build`:

1. Combined pdf is a markdown file called `combined.pdf.md`
2. Attempts to convert from pdf files instead of to pdf 

Can you suggest anything to fix?

## Combined markdown instead of pdf

When I set combined=true, the resulting combined file from `mkdocs build` is a **markdown** file that combines all other files, instead of a pdf.

Settings are as below:

```yaml
plugins:
  - search
  - pandoc:          # requires mkdocs-pandoc-plugin
      # enabled_if_env: ENABLE_PANDOC_EXPORT
      combined: true
```

## Attempts to convert from pdf

There are repeated errors in the terminal like this:

```bash
Unknown input format pdf
Pandoc can convert to PDF, but not from PDF.
```
With `combined=true` then the combined file is created as a markdown (as above). 

If I set `combined=false`, then no pdf files are created in the subdirectories of mkdocs_site/pandoc.
